name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Check code style
      run: ./gradlew lint
    - name: Build release APK after test
      run: |
        ./gradlew test
        ./gradlew assembleRelease
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: Upload code style logs
        path: ./app/build/reports/lint-results.html
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
    - name: Unit Test
      run: ./gradlew testDebugUnitTest

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }}
    - name: Upload app to telegram
        uses: appleboy/telegram-action@master
        with:
          to: 1017445984
          token: 1686259660:AAFimF05J0q5Kx_ZwJIB76qHJbN77qjC9-M
          message: successful build
          document: ./app/build/outputs/apk/debug/app-debug.apk
